#!/bin/bash
export TF_CPP_MIN_LOG_LEVEL=2
python3 vae/with_tf.py \
  --data_path ../data/springer/lang/english_400000.csv \
  --model_dir ../models/springer_vae \
  --max_doc 200 \
  --batch_size 1024 \
  --epochs 10000000
