#!/bin/bash
export TF_CPP_MIN_LOG_LEVEL=2
export py3=python3
export ETL_ROOT=`pwd`/externs/360-etl
export PYTHONPATH=$ETL_ROOT:`pwd`
export LOCAL_MODEL=true
export TABLE_GLOBAL='360_global'
export KAFKA_BROKERS="localhost:17811,localhost:9092"
export MODEL_HANDLERS="SpringerHandler,NaicsHandler"
export CONSUMERS="Article,Org"
export PRODUCERS="Article,Org"
export PRODUCER_CHUNKSIZE=100
#export MODEL_HANDLERS="NaicsHandler"
