#!/bin/bash
export TF_CPP_MIN_LOG_LEVEL=2
export py3=python3
export ETL_ROOT=
export PYTHONPATH=$ETL_ROOT:`pwd`
export LOCAL_MODEL=true
export KAFKA_BROKERS=localhost:17811,localhost:9092
export MODEL_HANDLERS=SpringerHandler,NaicsHandler
export CONSUMERS=Org,Article
export PRODUCERS=Article,Org
export PRODUCER_CHUNKSIZE=100
export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export AWS_REGION_KEY=
export AWS_S3_BUCKET=
