#!/bin/bash
export TF_CPP_MIN_LOG_LEVEL=2
export py3=python3
export ETL_ROOT=~/lab/360-etl
export PYTHONPATH=$ETL_ROOT:`pwd`
source $ETL_ROOT/dev_env_rawdata.sh
export LOCAL_MODEL=true
export TABLE_GLOBAL='360_global'
export KAFKA_BROKERS="localhost:9092,localhost:9093"
export MODEL_HANDLERS="SpringerHandler" #,NaicsHandler"
export MODEL_HANDLERS="NaicsHandler"
#$py3 julian/input/DTProducer.py
#$py3 julian/handler/springer_handler.py
#$py3 julian/handler/naics_handler.py
$py3 julian/handler/start_handlers.py
#$py3 julian/output/DTConsumer.py


find . -name __pycache__ -exec rm -rf {} \; 2> /dev/null
