#!/bin/bash
source ./julian/tools/common

source $ETL_ROOT/dev_env_rawdata.sh
#$py3 julian/input/DTProducer.py
$py3 julian/handler/start_handlers.py
#$py3 julian/output/DTConsumer.py


find . -name __pycache__ -exec rm -rf {} \; 2> /dev/null
