#!/bin/bash
export TF_CPP_MIN_LOG_LEVEL=2
python3 with_tf.py \
  --data_path ../data/springer/lang/english_tiny.csv \
  --model_dir ../models/springer_cnn_eng \
  --max_doc 50 \
  --batch_size 512 \
  --dropout 0.7 \
  --name springer
