#!/bin/bash
py3=python3
export ETL_ROOT=`pwd`/../360-etl
export PYTHONPATH=`pwd`/../360-etl:`pwd`
source $ETL_ROOT/dev_env_rawdata.sh
export LOCAL_MODEL=true
export TABLE_GLOBAL='360_global'
export KAFKA_BROKERS="localhost:9092,localhost:9093"

#$py3 julian/input/DTProducer.py
#$py3 julian/handler/springer_handler.py
$py3 julian/output/DTConsumer.py


find . -name __pycache__ -exec rm -rf {} \; 2> /dev/null
