#!/bin/bash
export py3=python3
export ETL_ROOT=~/lab/360-etl
export PYTHONPATH=`pwd`:$ETL_ROOT
source $ETL_ROOT/dev_env_rawdata.sh
export LOCAL_MODEL=true
export TABLE_GLOBAL='360_global'
export KAFKA_BROKERS="localhost:17811,localhost:9092"
export CONSUMERS="Article,Org"

#$py3 julian/input/DTProducer.py
#$py3 julian/handler/springer_handler.py
$py3 julian/output/DTConsumer.py


find . -name __pycache__ -exec rm -rf {} \; 2> /dev/null
